function map(){console.log('Original map.js');let arr,temp,t,t1,t2,t3,t4;let lengthSum=0,lengthSection=2;for(let m in mapList){t3=document.getElementsByTagName(m)[0];for(let i in mapList[m]){arr=mapList[m][i];t1=document.createElement('input');t1.type='checkbox';t1.onchange=function(){var el=this.nextElementSibling;if(this.checked)for(var i=0;i<el.children.length;i++){el.children[i].removeAttribute('hidden')}else for(var i=0;i<el.children.length;i++){el.children[i].setAttribute('hidden','')}};t3&&t3.appendChild(t1);t4=document.createElement('ul');t3&&t3.appendChild(t4);for(let j=0,l=arr.length;j<l;j++){t=arr[j];if(j===0){temp=document.createElement('a');temp.setAttribute('data-load_page',j+lengthSection+lengthSum);temp.innerHTML=t[0];t4.appendChild(temp)}
else{t1=document.createElement('li');t1.setAttribute('hidden','');temp=document.createElement('a');temp.setAttribute('data-load_page',j+lengthSection+lengthSum);temp.innerHTML=t[0];t1.appendChild(temp);t4.appendChild(t1);if(t[2]){t2=document.createElement('task-');t1.appendChild(t2);for(let k=0,l=t[2].length;k<l;k++){temp=document.createElement('a');temp.setAttribute('data-load_page',j+lengthSection+lengthSum+'-'+(k+1));temp.innerHTML=t[2][k];t2.appendChild(temp)}}}}
lengthSection+=arr.length}
lengthSum+=lengthSection;if(m==='map-list_1')
lengthSection=1;else lengthSection=0}
let found,foundTask;map.filter=function(val){arr=document.getElementsByTagName('map-content')[0].getElementsByTagName('ul');for(let i=0,l=arr.length;i<l;i++){t=arr[i].getElementsByTagName('a');found=foundTask=0;for(let j=0,l=t.length;j<l;j++){t1=t[j].parentElement;temp=t[j].innerHTML.toLowerCase();if(t1.tagName==='LI'){if(temp.indexOf(val)!==-1){found=1;t1.removeAttribute('hidden')}else{t1.setAttribute('hidden','')}}else if(t1.tagName==='TASK-'){if(temp.indexOf(val)!==-1){foundTask=1;t[j].removeAttribute('style');t1.removeAttribute('hidden');t1.parentElement.removeAttribute('hidden')}else{t[j].style.display='none'}}}
if(found||foundTask){arr[i].removeAttribute('hidden');arr[i].previousElementSibling.removeAttribute('hidden')}
else{arr[i].setAttribute('hidden','');arr[i].previousElementSibling.setAttribute('hidden','')}}
for(let i=0,l=arr.length;i<l;i++){temp=arr[i].firstElementChild.innerHTML.toLowerCase();if(temp.indexOf(val)!==-1){arr[i].removeAttribute('hidden')}}
if(val===''){for(let i=0,l=arr.length;i<l;i++){t1=arr[i].getElementsByTagName('li');if(arr[i].previousElementSibling.checked){for(let j=0,l=t1.length;j<l;j++){t1[j].removeAttribute('hidden')}}
else{for(let j=0,l=t1.length;j<l;j++){t1[j].setAttribute('hidden','')}}}}}
mapList=null;t=document.getElementById('map_list');t&&t.remove()} map();